function [InputWeight, HiddenBias] = AIS_ELM(InputWeight,HiddenBias,...
    NumberofHidden, NumberofTag, PosTag,TrainInput, NumberofValTag, ...
    PosValTag, ValInput)
NumberofInput = size(TrainInput, 2);;
[best_ab,best_fval,it,best_set,FE]=...
    optainet(InputWeight,HiddenBias,NumberofHidden,...
    NumberofTag, PosTag,TrainInput, NumberofValTag, ...
    PosValTag, ValInput);

InputWeight = reshape(best_ab(1:NumberofHidden*NumberofInput), ...
 NumberofHidden, NumberofInput);
HiddenBias = reshape(best_ab(NumberofHidden*NumberofInput+1:end),...
   NumberofHidden, 1);
end