function [InputWeight, HiddenBias] = AIS_ELM(InputWeight,HiddenBias,...
    NumberofHidden, NumberofTag, PosTag,TrainInput, NumberofValTag, ...
    PosValTag, ValInput)

[best_ab,best_fval,it,best_set,FE]=...
    optainet(InputWeight,HiddenBias,NumberofHidden,...
    NumberofTag, PosTag,TrainInput, NumberofValTag, ...
    PosValTag, ValInput);

InputWeight = reshape(best_ab(1:NumberofHidden*4), ...
 NumberofHidden, 4);
HiddenBias = reshape(best_ab(NumberofHidden*4+1:end),...
   NumberofHidden, 1);
end